'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {buildManifest,validateManifest,verifyManifestItem}=require('../scripts/lib/issue-1539-pinned-artifact-manifest');
const {parseSourceNoteIssue}=require('../scripts/lib/source-note-issue');
const snapshot=require('../audit/issue-1658-receipt-repair/current-live-snapshot.json');
function scenario(){const entries=snapshot.rows.map(r=>{const record=parseSourceNoteIssue(r.source.body).record;return {interview_issue_number:r.owner_issue,source_note_issue_number:r.source_issue,source_note_id:r.source_note_id,source_revision_id:r.source_revision_id,artifacts:record.artifacts};});const tree=entries.flatMap(e=>e.artifacts.map(a=>({type:'blob',path:a.ref.split(':')[1].split('@')[0],sha:a.git_blob_sha})));const manifest=buildManifest({repository:'liqiangcc/interview-lab',sourceSnapshot:{repository:'liqiangcc/xhs',ref:snapshot.source_ref},entries,treeEntries:tree,treeSha:'a'.repeat(40),scope:'explicit-selection'});return {manifest,entries};}
test('explicit selection accepts 13 exact owner/source pairs without impersonating fixed historical batches',()=>{const {manifest}=scenario();assert.equal(manifest.schema_version,'interview-note-pinned-artifact-manifest.v1');assert.equal(validateManifest(manifest).ok,true);assert.equal(manifest.items.length,13);});
for(const [name,mutate]of[
 ['missing item',m=>m.items.pop()],['missing selection',m=>delete m.selection],['duplicate owner',m=>{m.selection[1]=m.selection[0];}],['wrong source pair',m=>{m.selection[0].source_note_issue_number++;}],['unknown selection field',m=>{m.selection[0].other=true;}],['missing tree SHA',m=>delete m.verification.tree_sha],['wrong artifact ref',m=>{m.items[0].artifacts[0].ref=m.items[0].artifacts[0].ref.replace(/@[a-f0-9]{40}$/,'@'+'b'.repeat(40));}],['array selection entry',m=>{m.selection[0]=[];}],['non-array items',m=>{m.items={};}],
])test(`explicit selection rejects ${name}`,()=>{const {manifest}=scenario();mutate(manifest);assert.equal(validateManifest(manifest).ok,false);});
test('old schema retains fixed 30/17 scope rules',()=>{const {manifest}=scenario();manifest.schema_version='issue-1539-pinned-artifact-manifest.v1';manifest.scope='issue-1577-fixed-17';assert.equal(validateManifest(manifest).ok,false);});
test('manifest digest and live SourceNote bind each selected item',()=>{const {manifest}=scenario();const row=snapshot.rows[0];const request={issue_number:row.owner_issue,source_note_issue_number:row.source_issue,expected_source_revision_id:row.source_revision_id,pinned_artifact_manifest_sha256:manifest.digest};const record=parseSourceNoteIssue(row.source.body).record;assert.equal(verifyManifestItem(manifest,request,record).ok,true);record.source_note_id='xhs-note:wrong';assert.equal(verifyManifestItem(manifest,request,record).ok,false);});
